# weights: ./models/st_gcn.kinetics.pt
weights: ./output/kinetics-skeleton/best_model.pt
# feeder
feeder: feeder.feeder_gcn_kinetics.Feeder
test_feeder_args:
  data_path: ./data/kinetics-skeleton/val_data.npy
  label_path: ./data/kinetics-skeleton/val_label.pkl
  window_size: 300
# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test 
phase: test
device: [0,1]
test_batch_size: 64
