work_dir: ./output/kinetics-skeleton/
weights: ./output/kinetics-skeleton/epoch22_model.pt

# feeder
feeder: feeder.feeder_gcn_kinetics.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 300 
  data_path: ./data/kinetics-skeleton/train_data.npy
  label_path: ./data/kinetics-skeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/kinetics-skeleton/val_data.npy
  label_path: ./data/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [0,1]
batch_size: 64 
test_batch_size: 64

#optim
base_lr: 0.1
step: [100, 150]
num_epoch: 200
start_epoch: 23
# visulize and debug
log_interval: 50
save_interval: 2
eval_interval: 10


