work_dir: ./output/ntu-xsub/PB-GCN
# data_path: /media/ssd_storage/NTURGB+D/nturgb+d_skeletons
# missing_txt: /media/ssd_storage/NTURGB+D/samples_with_missing_skeletons.txt

# Data Loader
loader: feeder.pb_loader.ntuloader.NTULoader
test_loader_args:
  split_dir: ./data/NTU-RGB-D/xsub
  is_training: False
  signals:
    temporal_signal: True
    spatial_signal: True
    all_signal: False

# Model
model: net.pbgcn.st_gconv_resnet.STGraphConvResnet
model_args:
  layers_config: [[64, 64, 1], [64, 64, 1], [64, 64, 1], [64, 128, 2], [128, 128, 1], 
      [128, 128, 1], [128, 256, 2], [256, 256, 1], [256, 256, 1]]
  num_class: 60
  channel: 15
  window_size: 300
  num_joints: 25
  num_actors: 2
  graph: NTUGraph
  graph_args:
    labeling_mode: 'parts'
  mask_learning: True
  use_data_bn: True

# Training
device: [0]
test_batch_size: 64

# Evaluation
phase: test

# Initialization from checkpoint
# weights: ./pretrained_weights/crosssubject_weights.pth
