work_dir: ./output/ntu-xsub/PB-GCN
# data_path: /media/ssd_storage/NTURGB+D/nturgb+d_skeletons
# missing_txt: /media/ssd_storage/NTURGB+D/samples_with_missing_skeletons.txt

# Data Loader
feeder: feeder.pb_loader.ntuloader.NTULoader
train_feeder_args:
  split_dir: ./data/NTU-RGB-D/xsub
  signals:
    temporal_signal: True
    spatial_signal: True
    all_signal: False
test_feeder_args:
  split_dir: ./data/NTU-RGB-D/xsub
  is_training: False
  signals:
    temporal_signal: True
    spatial_signal: True
    all_signal: False

# Model
model: net.pbgcn.st_gconv_resnet.STGraphConvResnet
model_args:
  layers_config: [[64, 64, 1], [64, 64, 1], [64, 64, 1], [64, 128, 2], [128, 128, 1], 
      [128, 128, 1], [128, 256, 2], [256, 256, 1], [256, 256, 1]]
  num_class: 60
  channel: 15
  window_size: 300
  num_joints: 25
  num_actors: 2
  graph: NTUGraph
  graph_args:
    labeling_mode: 'parts'
  mask_learning: True
  use_data_bn: True

# Optimization
weight_decay: 0.0005
base_lr: 0.05
step: [20, 50, 70]

# Training
device: [0,1]
batch_size: 32
test_batch_size: 32
num_epoch: 80
save_interval: 5

# Evaluation
eval_interval: 5

# Initialization from checkpoint
# start_epoch: 5
# weights: /media/data_cifs/Kalpit/NTURGB+D/work_dir/cs/STGCN_parts_noaug/epoch65_model.pt

