weights: ./output/skating-skeleton-2/stgcn/stgcn_25_83.29.pt
work_dir: ./output/skating-skeleton-2/stgcn/
# feeder
feeder: feeder.feeder_gcn_skating_25.Feeder
test_feeder_args:
  window_size: 256
  data_path: ./data/SkatingSkeleton2/val_data_25.npy
  label_path: ./data/SkatingSkeleton2/val_label_25.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 10
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose25'
    strategy: 'spatial'

# test 
phase: test
device: 1
test_batch_size: 1

# debug
save_result: True
