weights: ./output/skating-skeleton-2/densenet/best_model.pt
work_dir: ./output/skating-skeleton-2/densenet
# feeder
feeder: feeder.feeder_densenet_skating_25.Skating
test_feeder_args:
  window_size: 256
  data_path: ./data/SkatingSkeleton2/val_data_25.npy
  label_path: ./data/SkatingSkeleton2/val_label_25.pkl

# model
model: net.densenet.DenseNet
model_args:
  in_channels: 2
  num_class: 10
  input_type: '25'
  depth: 148
  drop_rate: 0
  growth_rate: 12
  compression: 0.5
  num_init_features: 24
  bn_size: 4
  drop_rate: 0
  efficient: False
# test 
phase: test
device: 1
test_batch_size: 32
