work_dir: ./output/skating-skeleton-2/stgcn
# weights: ./output/skating-skeleton/best_model.pt

# feeder
feeder: feeder.feeder_gcn_skating_25.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 256 
  data_path: ./data/SkatingSkeleton2/train_data_25.npy
  label_path: ./data/SkatingSkeleton2/train_label_25.pkl
test_feeder_args:
  window_size: 256
  data_path: ./data/SkatingSkeleton2/val_data_25.npy
  label_path: ./data/SkatingSkeleton2/val_label_25.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 2
  num_class: 10
  edge_importance_weighting: True
  residual: True
  graph_args:
    layout: 'openpose25'
    strategy: 'hull3'

# training
device: [0,1]
batch_size: 64 
test_batch_size: 64

#optim
base_lr: 0.1
step: [150, 225]
num_epoch: 300

# visulize and debug
log_interval: 2
save_interval: 50
eval_interval: 1


