work_dir: ./output/skating-skeleton-2/densenet
# weights: ./output/skating-skeleton/best_model.pt

# feeder
feeder: feeder.feeder_densenet_skating_25.Skating
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 256 
  data_path: ./data/SkatingSkeleton2/train_data_25.npy
  label_path: ./data/SkatingSkeleton2/train_label_25.pkl
test_feeder_args:
  window_size: 256
  data_path: ./data/SkatingSkeleton2/val_data_25.npy
  label_path: ./data/SkatingSkeleton2/val_label_25.pkl

# model
model: net.densenet.DenseNet
model_args:
  in_channels: 2
  num_class: 10
  input_type: '25'
  depth: 148
  drop_rate: 0
  growth_rate: 12
  compression: 0.5  
  num_init_features: 24
  bn_size: 4
  drop_rate: 0
  efficient: False
# training
device: [0,1]
batch_size: 64 
test_batch_size: 64

# optim
base_lr: 0.1
step: [150, 225]
num_epoch: 300

# visulize and debug
log_interval: 2
save_interval: 50
eval_interval: 1


