weights: ./output/skating-skeleton-18/dstg/best_model.pt
work_dir: ./output/skating-skeleton-18/dstg/
# feeder
feeder: feeder.feeder_gcn_skating.Feeder
test_feeder_args:
  window_size: 256
  data_path: ./data/SkatingSkeleton2/val_data.npy
  label_path: ./data/SkatingSkeleton2/val_label.pkl

# model
model: net.dstg.DSTG
model_args:
  in_channels: 2
  num_class: 10
  depth: 148
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# test 
phase: test
device: 1
test_batch_size: 1

# debug
save_result: True
