weights: ./output/skating-skeleton-2/dstg/best_model.pt
work_dir: ./output/skating-skeleton-2/dstg/
# feeder
feeder: feeder.feeder_gcn_skating_25.Feeder
test_feeder_args:
  window_size: 256
  data_path: ./data/SkatingSkeleton2/val_data_25.npy
  label_path: ./data/SkatingSkeleton2/val_label_25.pkl

# model
model: net.dstg.DSTG
model_args:
  growth_rate: 12
  depth: 148
  compression: 0.5
  num_init_features: 24
  bn_size: 4
  tsize: 256
  in_channels: 2
  num_class: 10
  residual: True
  edge_importance_weighting: True
  edge_importance_depth: 1
  graph_args:
    layout: 'openpose25'
    strategy: 'spatial_hull'

# test 
phase: test
device: [0,1]
test_batch_size: 32

# debug
save_result: True
